#' Wide-to-long format conversion
#' 
#' Melts data frame with automatic variable creation and labeling given standard column headers
#' 
#' @param df data frame of CER measurements in wide format
#' @param CER label for the conditioned emotional response. Defaults to 'Freezing'.
#' @return new data frame
#' @author Jason Shumake
#' @details 
#' The wideToLong function takes as its input a data frame/table in wide format (one subject per row,
#' within-subject variables embedded in column names) and the measure of conditioned emotional response
#' (either an archived 'summary.txt' file from old lickometer data generated by the deprecated
#' LickometerTrans program, or a spreadsheet of freezing scores). The 'melt' function is used to return a
#' data frame/table in long format (each within-subject variable explicitly coded in separate columns).

#' Assumes the header follows a naming convention of 'ProtocolTimeTrial_Session'
#' where Time == 'Pre' or 'CS' ('Pre' referring to time before the CS and
#'               'CS' referring to time during the CS) 

#' Values for three variables are extracted from the header:
#' 
#' Session <- a combination of protocol and session
#' 
#' CS <- 'Pre' indicates the CER to context, 'CS' indicates the CER to the stimulus (e.g., tone)
#' 
#' Trial <- the trial number as determined by the helper function 'getTrial'
#' 
#' Example: 'ExtPre13_2' would refer to the pre-CS interval of the 13th trial of the second session of
#' extinction. The function would label each row of this column as follows:
#' 
#'    Session = 'Extinction 2'
#'    
#'    CS = 'Context'
#'    
#'    Trial = 13
#'    
#' @export
#' @importFrom reshape2 melt

wideToLong = function(df,CER='Freezing')
{
  df = melt(df, id.vars = 'Subject', value.name = CER)
  df$Session[grepl('^Ext\\w+_1$',df$variable)] = 'Extinction 1'
  df$Session[grepl('^Ext\\w+_2$',df$variable)] = 'Extinction 2'
  df$Session[grepl('^Rec\\w+_1$',df$variable)] = 'LTM'
  df$Session[grepl('^Rec\\w+_2$',df$variable)] = 'Reinstatement'
  df$Session[grepl('^Rec\\w+_3$',df$variable)] = 'Spont.Recover'
  df$CS[grepl('Pre',df$variable)] = 'Context'
  df$CS[grepl('CS',df$variable)] = 'Tone'
  for (i in 1:nrow(df))
  {
    df$Trial[i] = getTrial(df$variable[i])
  }
  if (is.data.table(df)) df$variable = NULL else df[,-'variable']
  return (df)
}